/**
 * OCI Wrapper API
 * Make it possible to query, modify and delete rules and rulegroups
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
var __param = (this && this.__param) || function (paramIndex, decorator) {
    return function (target, key) { decorator(target, key, paramIndex); }
};
var http_1 = require('@angular/http');
var core_1 = require('@angular/core');
require('rxjs/Rx');
var globals = require('../../../config.global');
/* tslint:disable:no-unused-variable member-ordering */
'use strict';
var cookies_service_1 = require("angular2-cookie/services/cookies.service");
var AddApi = (function () {
    function AddApi(http, basePath, cookie) {
        this.http = http;
        this.cookie = cookie;
        this.basePath = globals.OCI_URL + '/api/v1';
        this.defaultHeaders = new http_1.Headers({
            'Content-Type': 'application/json',
            Accept: 'application/json'
        });
        if (basePath) {
            this.basePath = basePath;
        }
    }
    AddApi.prototype.headerParser = function (header) {
        if (header.get('Authorization') != undefined) {
            header.set('Authorization', "Basic " + this.cookie.get('oci_session'));
            return header;
        }
        else {
            header.append('Authorization', "Basic " + this.cookie.get('oci_session'));
            return header;
        }
    };
    /**
     * add a DataSources.
     * The API offer the ability to add the datasource
     * @param body the name.
     */
    AddApi.prototype.datasourcePut = function (body, extraHttpRequestParams) {
        var path = this.basePath + '/datasource';
        var queryParameters = new http_1.URLSearchParams();
        var headerParams = this.headerParser(this.defaultHeaders);
        // verify required parameter 'body' is not null or undefined
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling datasourcePut.');
        }
        var requestOptions = {
            method: 'PUT',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(body);
        return this.http.request(path, requestOptions)
            .map(function (response) {
            if (response.status === 204) {
                return undefined;
            }
            else {
                return response.json();
            }
        });
    };
    /**
     * add a RuleGroup.
     * The API offer the ability to add the RuleGroup
     * @param body the name.
     */
    AddApi.prototype.rulegroupPut = function (body, extraHttpRequestParams) {
        var path = this.basePath + '/rulegroup';
        var queryParameters = new http_1.URLSearchParams();
        var headerParams = this.headerParser(this.defaultHeaders);
        // verify required parameter 'body' is not null or undefined
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling rulegroupPut.');
        }
        var requestOptions = {
            method: 'PUT',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(body);
        return this.http.request(path, requestOptions)
            .map(function (response) {
            if (response.status === 204) {
                return undefined;
            }
            else {
                return response.json();
            }
        });
    };
    /**
     * add a RuleSet.
     * The API offer the ability to add the RuleSet
     * @param body the name.
     */
    AddApi.prototype.rulesetPut = function (body, extraHttpRequestParams) {
        var path = this.basePath + '/ruleset';
        var queryParameters = new http_1.URLSearchParams();
        var headerParams = this.headerParser(this.defaultHeaders);
        // verify required parameter 'body' is not null or undefined
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling rulesetPut.');
        }
        var requestOptions = {
            method: 'PUT',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(body);
        return this.http.request(path, requestOptions)
            .map(function (response) {
            if (response.status === 204) {
                return undefined;
            }
            else {
                return response.json();
            }
        });
    };
    /**
     * add a ThresholdDef.
     * The API offer the ability to add the ThresholdDef
     * @param body the name.
     */
    AddApi.prototype.thresholdDefPut = function (body, extraHttpRequestParams) {
        var path = this.basePath + '/threshold_def';
        var queryParameters = new http_1.URLSearchParams();
        var headerParams = this.headerParser(this.defaultHeaders);
        // verify required parameter 'body' is not null or undefined
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling thresholdDefPut.');
        }
        var requestOptions = {
            method: 'PUT',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(body);
        return this.http.request(path, requestOptions)
            .map(function (response) {
            if (response.status === 204) {
                return undefined;
            }
            else {
                return response.json();
            }
        });
    };
    /**
     * add a Threshold.
     * The API offer the ability to add the Threshold
     * @param body the name.
     */
    AddApi.prototype.thresholdPut = function (body, extraHttpRequestParams) {
        var path = this.basePath + '/threshold';
        var queryParameters = new http_1.URLSearchParams();
        var headerParams = this.headerParser(this.defaultHeaders);
        // verify required parameter 'body' is not null or undefined
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling thresholdPut.');
        }
        var requestOptions = {
            method: 'PUT',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(body);
        return this.http.request(path, requestOptions)
            .map(function (response) {
            if (response.status === 204) {
                return undefined;
            }
            else {
                return response.json();
            }
        });
    };
    AddApi = __decorate([
        core_1.Injectable(),
        __param(1, core_1.Optional()), 
        __metadata('design:paramtypes', [http_1.Http, String, cookies_service_1.CookieService])
    ], AddApi);
    return AddApi;
}());
exports.AddApi = AddApi;
//# sourceMappingURL=AddApi.js.map